import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext, useEffect, useState } from 'react';
import AuthContexts from '../contexts/AuthContexts';


const Home: NextPage = () => {
  const { signIn, confirm, isCodeSent, loading } = useContext(AuthContexts);
  const [phoneNumber, setPhoneNumber] = useState<string>('');
  const [codeNumber, setCodeNumber] = useState<string>('');

  useEffect(() => {
    // console.log({phoneNumber})
  },[phoneNumber])

  useEffect(() => {
    // console.log({codeNumber})
  },[codeNumber])
  
  return (
    <div className="flex h-full flex-col justify-center items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-6 max-w-md mx-auto bg-white rounded-xl shadow-lg flex items-center space-x-4">
        <div>
          <div className="text-xl font-medium text-black">Login com Smartphone!</div>
          <div className="flex items-start flex-col justify-start">
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="phoneNumber">
                Celular
              </label>
              <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="phoneNumber" type="text" placeholder="" onChange={(e) => setPhoneNumber(e.target.value)} />
              <button className="mt-2 bg-indigo-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button" onClick={() => signIn({ phoneNumber })}>Enviar SMS</button>
            </div>
            { loading ? 
            <button type="button" className="bg-indigo-500 ..." disabled>
            <svg className="animate-spin h-5 w-5 mr-3 ..." viewBox="0 0 24 24">
            </svg>
            Processing...
          </button>
          : null}
            { isCodeSent ?
            <>
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="phoneNumber">
                Código
              </label>
              <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="phoneNumber" type="text" placeholder="" onChange={(e) => setCodeNumber(e.target.value)} />
              <button className="mt-2 bg-indigo-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button" onClick={() => confirm({ codeNumber })}>Login</button>
            </div>
            </>
            : null }
          </div>
        </div>
      </div>

      <div id="recaptcha-container"></div>

    </div>
  )
}

export default Home
