import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useContext, useEffect, useState } from 'react';
import AuthContexts from '../../contexts/AuthContexts';
import styles from '../../styles/Home.module.css'
import Router from 'next/router'

const Home: NextPage = () => {
  const { signOut, user } = useContext(AuthContexts);

  useEffect(() => {
    if(!user) {
      Router.push("/");
    }
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Olá <a href="https://nextjs.org">{user.name}</a>
        </h1>

        <p className={styles.description}>
          Dashboard
        </p>

        <button type="button" onClick={() => signOut()}>Voltar</button>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
